id = "xy-zed"
name = "XY-Zed Theme"
version = "0.1.1"
schema_version = 1
authors = ["Daniel Zarifpour <z@rifpour.xyz>"]
description = "🐈‍⬛ A sleek and sophisticated dark theme with vibrant, intelligent syntax highlighting. Please report issues ➩"
repository = "https://github.com/zarifpour/xy-zed"
